[package]
name = "tracing-perfetto"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
prost = "0.12"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
prost-build = "0.12"
protobuf-src = "2.0.1"
