[package]
name = "tracing-perfetto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
chrono = "0.4.38"
prost = "0.12"
rand = "0.8.5"
thread-id = "4.2.1"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
prost-build = "0.12"
protobuf-src = "2.0.1"
